apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-06-05T15:58:56Z"
  generation: 5
  labels:
    app: scaling-example
  name: scaling-example
  namespace: default
  resourceVersion: "7421"
  uid: eee25174-c798-42e4-9475-3a609fc30a1b
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: scaling-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      # Commented out so the file doesn't have a specious error
      #creationTimestamp: null
      labels:
        app: scaling-example
    spec:
      containers:
      - image: gcr.io/google-samples/kubernetes-bootcamp:v1
        imagePullPolicy: IfNotPresent
        name: kubernetes-bootcamp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2025-06-05T15:58:56Z"
    lastUpdateTime: "2025-06-05T15:59:05Z"
    message: ReplicaSet "scaling-example-6c95bc459" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-05T16:23:38Z"
    lastUpdateTime: "2025-06-05T16:23:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
