apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
    - name: liveness
      image: registry.k8s.io/busybox:1.27.2
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      startupProbe:
        # Restart on failure
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 2
        periodSeconds: 3
        failureThreshold: 3
      livenessProbe:
        # Restart on failure
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      readinessProbe:
        # Removed from matching services, can rejoin
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
