apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustom-deployment
  name: kustom-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kustom-deployment
  type: LoadBalancer
