apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustom-deployment
  name: kustom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustom-deployment
  template: # The template for the pod for this deployment
    metadata:
      labels:
        app: kustom-deployment
    spec:
      containers:
        - image: kicbase/echo-server:1.0
          name: echo-server
          resources: {}
