apiVersion: v1
kind: Service
metadata:
  labels:
    app: folder-deployment
  name: folder-deployment
spec:
  ports:
  -  port: 8080
     protocol: TCP
     targetPort: 8080
  selector:
    app: folder-deployment
  type: NodePort
status:
  loadBalancer: {}