apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: combined-deployment
  name: combined-deployment
spec:
  selector:
    matchLabels:
      app: combined-deployment
  template: # The template for the pod for this deployment
    metadata:
      labels:
        app: combined-deployment
    spec:
      containers:
      - image: kicbase/echo-server:1.0
        name: echo-server
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: combined-deployment
  name: combined-deployment
spec:
  ports:
  -  port: 8080
     protocol: TCP
     targetPort: 8080
  selector:
    app: combined-deployment
  type: NodePort
status:
  loadBalancer: {}