apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-deployment
  name: simple-deployment
spec:
  ports:
  # Could hard-code the nodePort, as in the line below.
  # Or skip to let kubernetes decide on the nodePort
  # - nodePort: 32663
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-deployment
  type: LoadBalancer
