apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-deployment
  name: simple-deployment
spec:
  selector:
    matchLabels:
      app: simple-deployment
  template: # The template for the pod for this deployment
    metadata:
      labels:
        app: simple-deployment
    spec:
      containers:
      - image: kicbase/echo-server:1.0
        name: echo-server
        resources: {}
