apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-deployment
  name: simple-deployment
spec:
  ports:
  - nodePort: 31213
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-deployment
  type: LoadBalancer
status:
  loadBalancer: {}